---
name: Docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check if release
        id: setup
        run: |
          echo "IS_RELEASE=${{
            github.event_name == 'push' && github.ref == 'refs/heads/main'
          }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v5

      - name: Upgrade jinja
        run: pip install -U jinja2

      - name: Install Python dependencies
        run: pip install -r requirements-doc.txt

      - name: Build
        run: |
          if [ "${{ steps.setup.outputs.IS_RELEASE }}" == "true" ]; then
            O="-t release"
          fi
          make html O="$O"

      - name: Publish
        if: ${{ steps.setup.outputs.IS_RELEASE == 'true' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          force_orphan: true
